// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NJInsurancePlatform.Data;

#nullable disable

namespace NJInsurancePlatform.Migrations
{
    [DbContext(typeof(InsuranceCorpDbContext))]
    [Migration("20221122151435_added policy request")]
    partial class addedpolicyrequest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "469a812a-dc44-4fb0-8437-efdb12f6ad38",
                            ConcurrencyStamp = "26a9f6c8-eac2-4dd7-b4b2-364fcb471b80",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "c655842c-8a18-424c-b65b-0d4ce96fd2c5",
                            ConcurrencyStamp = "e5d2c3df-d865-458d-801a-ffd847e44029",
                            Name = "Beneficiary",
                            NormalizedName = "BENEFICIARY"
                        },
                        new
                        {
                            Id = "2d5debc0-f21f-45e2-ada1-08c7ccbfa8e9",
                            ConcurrencyStamp = "74b1f57f-1609-42b9-8438-870bbc37fe67",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "63419f5d-1aa3-4855-a9a3-d7038c6ea6e7",
                            ConcurrencyStamp = "e811e260-3b90-44e5-a2ad-908be3a3da2a",
                            Name = "Pending",
                            NormalizedName = "PENDING"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "469a812a-dc44-4fb0-8437-efdb12f6ad38"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb7",
                            RoleId = "2d5debc0-f21f-45e2-ada1-08c7ccbfa8e9"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb8",
                            RoleId = "c655842c-8a18-424c-b65b-0d4ce96fd2c5"
                        },
                        new
                        {
                            UserId = "a8d97fa0-a27b-4431-9422-2ee1a8d86e21",
                            RoleId = "2d5debc0-f21f-45e2-ada1-08c7ccbfa8e9"
                        },
                        new
                        {
                            UserId = "b2d66bff-ebfb-46df-836d-80abd3c0c2a5",
                            RoleId = "2d5debc0-f21f-45e2-ada1-08c7ccbfa8e9"
                        },
                        new
                        {
                            UserId = "08baab79-3fb7-4da3-835e-c0790db0fb0c",
                            RoleId = "2d5debc0-f21f-45e2-ada1-08c7ccbfa8e9"
                        },
                        new
                        {
                            UserId = "09b11af0-e332-47c6-8857-a53e35e7b0e5",
                            RoleId = "2d5debc0-f21f-45e2-ada1-08c7ccbfa8e9"
                        },
                        new
                        {
                            UserId = "582b6b5a-e3e8-4fbf-9eec-1d1f57759f4f",
                            RoleId = "c655842c-8a18-424c-b65b-0d4ce96fd2c5"
                        },
                        new
                        {
                            UserId = "b872914d-512d-4317-988e-d175d2331b79",
                            RoleId = "c655842c-8a18-424c-b65b-0d4ce96fd2c5"
                        },
                        new
                        {
                            UserId = "708bc36e-060f-4162-b23c-d78a4aa482ad",
                            RoleId = "c655842c-8a18-424c-b65b-0d4ce96fd2c5"
                        },
                        new
                        {
                            UserId = "cd8d4841-59ce-4a1d-b7d3-90cfd268f660",
                            RoleId = "c655842c-8a18-424c-b65b-0d4ce96fd2c5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Beneficiary", b =>
                {
                    b.Property<Guid>("BeneficiaryMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<Guid?>("TransactionMUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BeneficiaryMUID");

                    b.HasIndex("TransactionMUID");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Bill", b =>
                {
                    b.Property<Guid>("BillMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("MinimumPayment")
                        .HasColumnType("float");

                    b.Property<DateTime>("PolicyDueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PolicyMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BillMUID");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            BillMUID = new Guid("f46090ed-d574-4456-8e18-97150ff885ed"),
                            Balance = 799.34000000000003,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3477),
                            MinimumPayment = 123.98999999999999,
                            PolicyDueDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3468),
                            PolicyMUID = new Guid("a61a15af-6a7d-4e82-9659-c5003721f5ea"),
                            Status = "status"
                        },
                        new
                        {
                            BillMUID = new Guid("417a8279-0227-43c4-8504-c4396860ada0"),
                            Balance = 509.33999999999997,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3494),
                            MinimumPayment = 283.99000000000001,
                            PolicyDueDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3486),
                            PolicyMUID = new Guid("abdafd4a-48ff-4f1a-bcc6-fd3dd2c659a5"),
                            Status = "status"
                        },
                        new
                        {
                            BillMUID = new Guid("c28330de-a718-465b-9772-5b28ad6395e8"),
                            Balance = 109.34,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3508),
                            MinimumPayment = 129.09,
                            PolicyDueDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3503),
                            PolicyMUID = new Guid("67bb56de-01c9-42e2-b066-eea2c082f06f"),
                            Status = "status"
                        },
                        new
                        {
                            BillMUID = new Guid("9b7d532c-62a8-4a8d-96d9-6a7a80b118d4"),
                            Balance = 278.33999999999997,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3524),
                            MinimumPayment = 449.08999999999997,
                            PolicyDueDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3517),
                            PolicyMUID = new Guid("46c76123-4e2c-4cce-95fa-0646268c5b1d"),
                            Status = "status"
                        });
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Claim", b =>
                {
                    b.Property<Guid>("ClaimMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimUserDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CustomerMUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfClaim")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyMUID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaimMUID");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentEmployer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CurrentZipcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryPolicyHolder")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("PolicyMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("CustomerMUID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Faq", b =>
                {
                    b.Property<Guid>("FaqMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaqMUID");

                    b.ToTable("Faqs");
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.GroupRoom", b =>
                {
                    b.Property<Guid>("GroupMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("GroupMUID");

                    b.ToTable("GroupRooms");
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.GroupRoomMessage", b =>
                {
                    b.Property<Guid>("GroupRoomMessageMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupRoomMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<Guid>("SenderMUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupRoomMessageMUID");

                    b.ToTable("GroupRoomMessages");

                    b.HasData(
                        new
                        {
                            GroupRoomMessageMUID = new Guid("82ba35e1-0c52-4f91-8ff3-7ba15a87c237"),
                            GroupRoomMUID = new Guid("f4f42d43-4d51-43a9-b398-5430131efd2a"),
                            Message = "Hello, Can you please Help Me?",
                            SenderMUID = new Guid("d9ef788c-a3f8-48b3-92ce-804170aba836")
                        },
                        new
                        {
                            GroupRoomMessageMUID = new Guid("7a9ff0a2-6386-4094-8ae8-9240611eef7a"),
                            GroupRoomMUID = new Guid("80d2744e-2de6-47cc-97d1-05f8a0794f6c"),
                            Message = "yes, How Can I Help you?",
                            SenderMUID = new Guid("a7071f27-db08-47fb-a05a-0a7da44b44c4")
                        },
                        new
                        {
                            GroupRoomMessageMUID = new Guid("e857e40b-d4d6-45dc-912f-4be6fc749c2d"),
                            GroupRoomMUID = new Guid("7e5319b1-4285-4811-bf88-c8542ac4bfa1"),
                            Message = "I have a question About My Policy",
                            SenderMUID = new Guid("a7071f27-db08-47fb-a05a-0a7da44b44c4")
                        },
                        new
                        {
                            GroupRoomMessageMUID = new Guid("4db427d8-8084-4987-9783-ef1154a0627b"),
                            GroupRoomMUID = new Guid("858efa88-5226-47e5-8bd0-80546b2f469d"),
                            Message = "Sure, What would you like to know?",
                            SenderMUID = new Guid("93fa9038-9c45-42cf-993b-fc3d15764f18")
                        });
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BillMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CardExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CheckImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CheckNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebitOrCredit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayerFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("PaymentMUID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentMUID = new Guid("d3bfa2b2-a707-412f-9c4d-cbf1ec275693"),
                            AccountNumber = "2345643",
                            AdditionalInfo = "Additional info",
                            Amount = 123.98999999999999,
                            BankName = "Spring Savings",
                            BillMUID = new Guid("f46090ed-d574-4456-8e18-97150ff885ed"),
                            CardExpireDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3601),
                            CardNumber = "123498732",
                            CheckImage = "check Image",
                            CheckNumber = 123,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3607),
                            DebitOrCredit = "debit",
                            PaidDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3590),
                            PayerFirstName = "Jillian",
                            PayerLastName = "Flowers",
                            PaymentMethod = "visa",
                            RoutingNumber = "2345432",
                            ZipCode = "12345"
                        },
                        new
                        {
                            PaymentMUID = new Guid("0b8e18c5-0b17-4bc1-b2a3-00abe6fb5e72"),
                            AccountNumber = "2345643",
                            AdditionalInfo = "Additional info",
                            Amount = 234.88999999999999,
                            BankName = "Peoples Savings",
                            BillMUID = new Guid("417a8279-0227-43c4-8504-c4396860ada0"),
                            CardExpireDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3619),
                            CardNumber = "123498732",
                            CheckImage = "check Image",
                            CheckNumber = 345,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3624),
                            DebitOrCredit = "credit",
                            PaidDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3610),
                            PayerFirstName = "Fred",
                            PayerLastName = "Sanders",
                            PaymentMethod = "mastercard",
                            RoutingNumber = "2345432",
                            ZipCode = "12345"
                        },
                        new
                        {
                            PaymentMUID = new Guid("0fc63b41-88b2-4ad9-9035-0951611d62ae"),
                            AccountNumber = "2345643",
                            AdditionalInfo = "Additional info",
                            Amount = 563.99000000000001,
                            BankName = "Bank of Nova Scotia",
                            BillMUID = new Guid("c28330de-a718-465b-9772-5b28ad6395e8"),
                            CardExpireDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3633),
                            CardNumber = "123498732",
                            CheckImage = "check Image",
                            CheckNumber = 4532,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3636),
                            DebitOrCredit = "credit",
                            PaidDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3630),
                            PayerFirstName = "Phillis",
                            PayerLastName = "McMahon",
                            PaymentMethod = "visa",
                            RoutingNumber = "2345432",
                            ZipCode = "12345"
                        },
                        new
                        {
                            PaymentMUID = new Guid("0b73fbd0-eb85-42c4-a634-e8ee78d81218"),
                            AccountNumber = "2345643",
                            AdditionalInfo = "Additional info",
                            Amount = 58.990000000000002,
                            BankName = "Bank of the Oranges",
                            BillMUID = new Guid("9b7d532c-62a8-4a8d-96d9-6a7a80b118d4"),
                            CardExpireDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3648),
                            CardNumber = "123498732",
                            CheckImage = "check Image",
                            CheckNumber = 9870,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3652),
                            DebitOrCredit = "credit",
                            PaidDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3642),
                            PayerFirstName = "katherine",
                            PayerLastName = "Rivera",
                            PaymentMethod = "visa",
                            RoutingNumber = "2345432",
                            ZipCode = "12345"
                        });
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Policy", b =>
                {
                    b.Property<Guid>("PolicyMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AnnualLimitOfCoverage")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("Deductible")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("NameOfPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("OutOfPocketLimit")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<bool>("Pending")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PolicyEnd_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolicyNumber")
                        .HasColumnType("int");

                    b.Property<string>("PolicyOwner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PolicyPaidOffAmount")
                        .HasColumnType("float");

                    b.Property<bool>("PolicyPaymentisDue")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PolicyStart_Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("PolicyTotalAmount")
                        .HasColumnType("float");

                    b.HasKey("PolicyMUID");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            PolicyMUID = new Guid("a61a15af-6a7d-4e82-9659-c5003721f5ea"),
                            AnnualLimitOfCoverage = 14999.99,
                            Deductible = 100.25,
                            NameOfPolicy = "Dental Gold",
                            OutOfPocketLimit = 999.99000000000001,
                            Pending = false,
                            PolicyEnd_Date = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3133),
                            PolicyNumber = 1234,
                            PolicyOwner = "Patrick Leon",
                            PolicyPaidOffAmount = 0.0,
                            PolicyPaymentisDue = false,
                            PolicyStart_Date = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3084),
                            PolicyTotalAmount = 35000.0
                        },
                        new
                        {
                            PolicyMUID = new Guid("abdafd4a-48ff-4f1a-bcc6-fd3dd2c659a5"),
                            AnnualLimitOfCoverage = 14999.99,
                            Deductible = 100.25,
                            NameOfPolicy = "Health Platinum",
                            OutOfPocketLimit = 999.99000000000001,
                            Pending = false,
                            PolicyEnd_Date = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3146),
                            PolicyNumber = 4567,
                            PolicyOwner = "Eric Daley",
                            PolicyPaidOffAmount = 0.0,
                            PolicyPaymentisDue = false,
                            PolicyStart_Date = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3143),
                            PolicyTotalAmount = 35000.0
                        },
                        new
                        {
                            PolicyMUID = new Guid("67bb56de-01c9-42e2-b066-eea2c082f06f"),
                            AnnualLimitOfCoverage = 14999.99,
                            Deductible = 100.25,
                            NameOfPolicy = "Eye Emarald",
                            OutOfPocketLimit = 999.99000000000001,
                            Pending = false,
                            PolicyEnd_Date = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3154),
                            PolicyNumber = 78910,
                            PolicyOwner = "Nikosi Thom",
                            PolicyPaidOffAmount = 0.0,
                            PolicyPaymentisDue = false,
                            PolicyStart_Date = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3151),
                            PolicyTotalAmount = 35000.0
                        },
                        new
                        {
                            PolicyMUID = new Guid("46c76123-4e2c-4cce-95fa-0646268c5b1d"),
                            AnnualLimitOfCoverage = 14999.99,
                            Deductible = 100.25,
                            NameOfPolicy = "Eye Emarald",
                            OutOfPocketLimit = 999.99000000000001,
                            Pending = false,
                            PolicyEnd_Date = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3160),
                            PolicyNumber = 769564,
                            PolicyOwner = "Leona wilson",
                            PolicyPaidOffAmount = 0.0,
                            PolicyPaymentisDue = false,
                            PolicyStart_Date = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3158),
                            PolicyTotalAmount = 35000.0
                        });
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.PolicyRequest", b =>
                {
                    b.Property<Guid>("RequestMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyMUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RequestMUID");

                    b.ToTable("PolicyRequests");
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionMUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PaymentAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PolicyMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isPaymentComplete")
                        .HasColumnType("bit");

                    b.HasKey("TransactionMUID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionMUID = new Guid("76098a5e-bcda-46be-9cf3-a19f24d14018"),
                            CustomerMUID = new Guid("7e46ae9d-ff19-47da-ae69-922069555efb"),
                            PaymentAmount = 1199.78,
                            PaymentDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3405),
                            PolicyMUID = new Guid("a61a15af-6a7d-4e82-9659-c5003721f5ea"),
                            isPaymentComplete = true
                        },
                        new
                        {
                            TransactionMUID = new Guid("530f62a1-8730-4784-bb71-a257136dd9f6"),
                            CustomerMUID = new Guid("0d7a4ff8-5b33-44bf-a0fe-bd0f696187f1"),
                            PaymentAmount = 2109.7800000000002,
                            PaymentDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3414),
                            PolicyMUID = new Guid("abdafd4a-48ff-4f1a-bcc6-fd3dd2c659a5"),
                            isPaymentComplete = true
                        },
                        new
                        {
                            TransactionMUID = new Guid("f752a2a0-7300-42ba-beab-dc65992ca945"),
                            CustomerMUID = new Guid("3498cdd0-6913-4c08-b29f-5291f28201ce"),
                            PaymentAmount = 109.08,
                            PaymentDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3417),
                            PolicyMUID = new Guid("67bb56de-01c9-42e2-b066-eea2c082f06f"),
                            isPaymentComplete = false
                        },
                        new
                        {
                            TransactionMUID = new Guid("3287bca8-d9dc-4f75-94ca-227cfb4c72da"),
                            CustomerMUID = new Guid("3498cdd0-6913-4c08-b29f-5291f28201ce"),
                            PaymentAmount = 189.05000000000001,
                            PaymentDate = new DateTime(2022, 11, 22, 10, 14, 34, 639, DateTimeKind.Local).AddTicks(3422),
                            PolicyMUID = new Guid("46c76123-4e2c-4cce-95fa-0646268c5b1d"),
                            isPaymentComplete = false
                        });
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid?>("BeneficiaryMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentEmployer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CurrentZipcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("CustomerMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimaryPolicyHolder")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid?>("PolicyMUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SSN")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82801642-b639-4df1-8842-97a41558b695",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEEc2KuMeBtQxxA9I4jnDNDxZ0fxAQBdJOhUno3z1KfhtCnoEebHpEWOKUAcEzQGIZw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30021faf-55a8-4fb0-8d2f-6e1baf588a30",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            Active = false,
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "admin",
                            IsPrimaryPolicyHolder = false
                        },
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe0d8cef-fe98-4585-9caf-817ce68c70c7",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "CUSTOMER",
                            PasswordHash = "AQAAAAEAACcQAAAAEA5mvQ0anATxdvroPS3ZBD+Q9h9Ab1JBq6rhcpuq2VKWagPrt9nd/wKFZDPegKNmmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f8906e28-1be0-4886-a55d-a1558c0212fe",
                            TwoFactorEnabled = false,
                            UserName = "customer",
                            Active = false,
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "customer",
                            IsPrimaryPolicyHolder = false
                        },
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "89219911-f6ba-46ef-9699-23e9e85821f1",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "BENEFICIARY",
                            PasswordHash = "AQAAAAEAACcQAAAAEK3jVk10W+LEgIf9sOS5IROODJk2dKNYMqDjRQvaJzo0dBBx9NP58b3xZuoQe2FjRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3edddd3-bd13-46ab-bf8b-7a4eec48f6d7",
                            TwoFactorEnabled = false,
                            UserName = "beneficiary",
                            Active = false,
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "beneficiary",
                            IsPrimaryPolicyHolder = false
                        },
                        new
                        {
                            Id = "a8d97fa0-a27b-4431-9422-2ee1a8d86e21",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "205067f5-22fb-40af-91f4-0701e52ce8d0",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "PATO",
                            PasswordHash = "AQAAAAEAACcQAAAAEHjl16whxjDYafLwFfrNh1CIWrKriFeIr7mmrcTsIjP1eAfjVBxwmHu/U/Ku7CQUiA==",
                            PhoneNumber = "2019878709",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6363d0b2-5f15-4ee4-b9e5-688b1d66a039",
                            TwoFactorEnabled = false,
                            UserName = "Pato",
                            Active = true,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 667, DateTimeKind.Local).AddTicks(9486),
                            CurrentAddress = "123 Elm street",
                            CurrentCity = "Milwaukee",
                            CurrentEmployer = "Alphabet Corp",
                            CurrentState = "Wisconsin",
                            CurrentZipcode = "7897678",
                            CustomerMUID = new Guid("7e46ae9d-ff19-47da-ae69-922069555efb"),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "PatrickL@mymail.com",
                            FirstName = "Patrick",
                            Gender = "male",
                            IsPrimaryPolicyHolder = true,
                            LastName = "Leon",
                            LicenseNumber = "39kh8087hf",
                            PolicyMUID = new Guid("a61a15af-6a7d-4e82-9659-c5003721f5ea"),
                            SSN = "123456789"
                        },
                        new
                        {
                            Id = "b2d66bff-ebfb-46df-836d-80abd3c0c2a5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b4cbd60-4973-4c32-979c-8e1506497737",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ERICD@MYMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEE1kDV3rYlVxcopypEF9UlSLHt5mhCW4wzCm1eEhU/KC8GeW/Htb3uFe6hhlClvgxA==",
                            PhoneNumber = "8790985467",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "95b4560b-c481-4b56-b62e-ab6074832483",
                            TwoFactorEnabled = false,
                            UserName = "EricD@mymail.com",
                            Active = true,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 678, DateTimeKind.Local).AddTicks(8975),
                            CurrentAddress = "456 main street",
                            CurrentCity = "Baltimore",
                            CurrentEmployer = "Xillon Co",
                            CurrentState = "Maryland",
                            CurrentZipcode = "7897678",
                            CustomerMUID = new Guid("0d7a4ff8-5b33-44bf-a0fe-bd0f696187f1"),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "EricD@mymail.com",
                            FirstName = "Eric",
                            Gender = "male",
                            IsPrimaryPolicyHolder = true,
                            LastName = "Daley",
                            LicenseNumber = "39kh8087hf",
                            PolicyMUID = new Guid("abdafd4a-48ff-4f1a-bcc6-fd3dd2c659a5"),
                            SSN = "123456789"
                        },
                        new
                        {
                            Id = "08baab79-3fb7-4da3-835e-c0790db0fb0c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8c6f8f9d-40b8-41bd-82bb-b29be81aa951",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "NIKOSIT@MYMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKIC82xI2jAoP0wTJ5fAyZQ3JtOQb9JCCKoDVwwpmUia3bWI4hHeAy40lu3Jq7GNlg==",
                            PhoneNumber = "8790985467",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d51dd313-94b8-4656-aca0-13d96ef457a9",
                            TwoFactorEnabled = false,
                            UserName = "NikosiT@mymail.com",
                            Active = true,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 687, DateTimeKind.Local).AddTicks(6166),
                            CurrentAddress = "789 Grove street",
                            CurrentCity = "Rockville",
                            CurrentEmployer = "techumseh International",
                            CurrentState = "Maryland",
                            CurrentZipcode = "7897678",
                            CustomerMUID = new Guid("3498cdd0-6913-4c08-b29f-5291f28201ce"),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "NikosiT@mymail.com",
                            FirstName = "Nikosi",
                            Gender = "female",
                            IsPrimaryPolicyHolder = true,
                            LastName = "Thom",
                            LicenseNumber = "39kh8087hf",
                            PolicyMUID = new Guid("67bb56de-01c9-42e2-b066-eea2c082f06f"),
                            SSN = "123456789"
                        },
                        new
                        {
                            Id = "09b11af0-e332-47c6-8857-a53e35e7b0e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2333880-36a4-43e9-8f40-e45296caef61",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "LEONAW@MYMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDodlYyIjC/+R8lksRgXCgILEgzKmz+kP3gyjMVC4cgBSlr4o55wmfMgGai94E9xAQ==",
                            PhoneNumber = "8790985467",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "51b0fd82-ca95-4a0d-a314-285ddef3cb85",
                            TwoFactorEnabled = false,
                            UserName = "LeonaW@mymail.com",
                            Active = true,
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 699, DateTimeKind.Local).AddTicks(391),
                            CurrentAddress = "3464 Brinkly street",
                            CurrentCity = "Gathersburg",
                            CurrentEmployer = "Brimson distributers",
                            CurrentState = "Maryland",
                            CurrentZipcode = "7897678",
                            CustomerMUID = new Guid("3498cdd0-6913-4c08-b29f-5291f28201ce"),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "LeonaW@mymail.com",
                            FirstName = "Leona",
                            Gender = "female",
                            IsPrimaryPolicyHolder = true,
                            LastName = "Wilson",
                            LicenseNumber = "39kh8087hf",
                            PolicyMUID = new Guid("46c76123-4e2c-4cce-95fa-0646268c5b1d"),
                            SSN = "123456789"
                        },
                        new
                        {
                            Id = "582b6b5a-e3e8-4fbf-9eec-1d1f57759f4f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "141b0fdd-97e0-459f-9333-4090a0440919",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ANDREAB@MYMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKC5uNaGnplCEBO0dlZ58v/kRVmaCdrWT9ozFzrJ5LABTGrnw1Scyf4vTINDNeYebg==",
                            PhoneNumber = "8790985467",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "20c7fd44-0dc1-4922-8dcd-fe1b239d26ee",
                            TwoFactorEnabled = false,
                            UserName = "AndreaB@mymail.com",
                            Active = true,
                            BeneficiaryMUID = new Guid("6808f1f0-47c1-4136-b775-b1f6ffc541fd"),
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 708, DateTimeKind.Local).AddTicks(7393),
                            CustomerMUID = new Guid("7e46ae9d-ff19-47da-ae69-922069555efb"),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "AndreaB@mymail.com",
                            FirstName = "Andrea",
                            Gender = "female",
                            IsPrimaryPolicyHolder = false,
                            LastName = "Bogataw",
                            LicenseNumber = "39kh8087hf",
                            SSN = "123456789"
                        },
                        new
                        {
                            Id = "b872914d-512d-4317-988e-d175d2331b79",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f26c9c22-7f0b-4139-818d-e8eac429c152",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "CYNTHIAS@MYMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEs2PhsHAmEayFjzLP4HJ12RewRCXoQqFGqMYnGrr0D5yUoZ5OGv0aNxuTOdF4mktQ==",
                            PhoneNumber = "8790985467",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d594f7f-5b54-4146-bea2-e12586a757f3",
                            TwoFactorEnabled = false,
                            UserName = "CynthiaS@mymail.com",
                            Active = true,
                            BeneficiaryMUID = new Guid("54d5eae1-ee39-4f2d-8535-5f610d2e1cff"),
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 718, DateTimeKind.Local).AddTicks(4128),
                            CustomerMUID = new Guid("0d7a4ff8-5b33-44bf-a0fe-bd0f696187f1"),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "CynthiaS@mymail.com",
                            FirstName = "Cynthia",
                            Gender = "female",
                            IsPrimaryPolicyHolder = false,
                            LastName = "Smithers",
                            LicenseNumber = "39k8ew8087hf",
                            SSN = "123456789"
                        },
                        new
                        {
                            Id = "708bc36e-060f-4162-b23c-d78a4aa482ad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4fdc9ba4-88e0-41d2-a23a-0dc97f40460c",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "BRITNEYG@MYMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEES1mWcscX5fbIGH6ock3Z1td0kCRH6abqbYx6urx+GjcPeX5kZd3AJwO3bJpE9MQw==",
                            PhoneNumber = "8790985467",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a11b088a-e04b-4809-b755-368ce074f299",
                            TwoFactorEnabled = false,
                            UserName = "BritneyG@mymail.com",
                            Active = true,
                            BeneficiaryMUID = new Guid("78d9cd41-acde-48fc-baa9-29b5065af159"),
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 728, DateTimeKind.Local).AddTicks(3407),
                            CustomerMUID = new Guid("3498cdd0-6913-4c08-b29f-5291f28201ce"),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "BritneyG@mymail.com",
                            FirstName = "Brittney",
                            Gender = "female",
                            IsPrimaryPolicyHolder = false,
                            LastName = "Giles",
                            LicenseNumber = "39k8ew8087hf",
                            SSN = "123456789"
                        },
                        new
                        {
                            Id = "cd8d4841-59ce-4a1d-b7d3-90cfd268f660",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cec64649-4ced-481a-97e3-448267ffadb0",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "JOANAM@MYMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAKTwT4T5e8RWffVPtTA5K9FUMmk336+9sQlRdQLa6Xf/N/NuRy8ARgp+4gRX0BHUw==",
                            PhoneNumber = "8790985467",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c469496d-2a88-4149-9915-36fb05c1f54b",
                            TwoFactorEnabled = false,
                            UserName = "JoanaM@mymail.com",
                            Active = true,
                            BeneficiaryMUID = new Guid("fa75877d-66a1-4f63-b8fa-d2cdb59fbdd1"),
                            CreatedDate = new DateTime(2022, 11, 22, 10, 14, 34, 736, DateTimeKind.Local).AddTicks(9718),
                            CustomerMUID = new Guid("3498cdd0-6913-4c08-b29f-5291f28201ce"),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "JoanaM@mymail.com",
                            FirstName = "Joana",
                            Gender = "female",
                            IsPrimaryPolicyHolder = false,
                            LastName = "Martin",
                            LicenseNumber = "39k8ew8087hf",
                            SSN = "123456789"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Beneficiary", b =>
                {
                    b.HasOne("NJInsurancePlatform.Models.Transaction", null)
                        .WithMany("ListOfPolicyBeneficiariesMUIDs")
                        .HasForeignKey("TransactionMUID");
                });

            modelBuilder.Entity("NJInsurancePlatform.Models.Transaction", b =>
                {
                    b.Navigation("ListOfPolicyBeneficiariesMUIDs");
                });
#pragma warning restore 612, 618
        }
    }
}
